//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Program
{
    static void Main(string[] args)
    {
        //Factory.Client.Demo();
        //AbstractFactory.Client.Demo();
        //Singleton.Client.Demo();
        //Builder.Client.Demo();
        //Adapter.Client.Demo();
        //Bridge.Client.Demo();
        //Composite.Client.Demo();
        //Decorator.Client.Demo();
        //Facade.Client.Demo();
        //Flyweight.Client.Demo();
        //Proxy.Client.Demo();
        //Filter.Client.Demo();
        //ChainOfResponsibility.Client.Demo();
        //ChainOfResponsibility.LoadExample.Client.Demo();
        //Command.Client.Demo();
        //Interpreter.Client.Demo();
        //Iterator.Client.Demo();
        //Mediator.Client.Demo();
        //Memento.Client.Demo();
        //Observer.Client.Demo();
        //State.Client.Demo();
        //Strategy.Client.Demo();
        //Template.Client.Demo();
        //Visitor.Client.Demo();
        //NullObject.Client.Demo();
        //MVC.Client.Demo();
        Prototype.Client.Demo();
    }

}

